name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install ubuntu libs
      run: sudo apt-get install mlocate nasm wget pkg-config libglfw3-dev cython python-pyqt5 python-pyqt5.qtsvg
    - name: ffmpeg
      run: |
        echo "mrs -----FFMPEG"
        wget https://ffmpeg.org/releases/ffmpeg-4.2.1.tar.bz2
        tar -xf ffmpeg-4.2.1.tar.bz2
        cd ffmpeg-4.2.1
        ./configure --enable-debug --disable-stripping --disable-doc --disable-autodetect --enable-zlib --disable-everything
        --enable-filter='aformat,aresample,asetnsamples,asettb,copy,format,fps,hflip,palettegen,paletteuse,settb,scale,transpose,vflip'
        --disable-programs --enable-avdevice --enable-swresample 
        --enable-bsf='aac_adtstoasc,h264_mp4toannexb,hevc_mp4toannexb,mpeg4_unpack_bframes,vp9_superframe'
        --enable-encoder='gif,png,mjpeg'
        --enable-demuxer='aac,aiff,concat,gif,image_jpeg_pipe,image_pgm_pipe,image_png_pipe,rawvideo,mp3,mp4,mov,wav,asf,avi,image_webp_pipe,flac,matroska,mpegts'
        --enable-decoder='alac,mjpeg,png,rawvideo,mp3,pcm_s16le,pcm_s16be,mpeg4,aac,gif,pgm,flac,h263,msmpeg4v1,msmpeg4v2,msmpeg4v3,vc1,vp8,webp,h264'
        --enable-parser='mjpeg,png,h264,mpeg4video,aac,flac,hevc,vp8,vp9'
        --enable-muxer='gif,image2,mp4,mov,ipod'
        --enable-protocol='file,http' --prefix=$HOME

        ./configure --prefix=$HOME --disable-autodetect
        make -j8
        echo "mrs -----FFMPEG END"
        make install 
        echo $?
        ls 
        sudo updatedb
    - name: Create repo with needed sxplayer
      run: |
        echo "mrs -----WHO AM I"
        lsb_release -a
        echo "mrs -----LOCATE"
        locate libavformat.pc
        echo "mrs -----LIST DIRECTORIES"
        ls  
        echo "mrs -----CLONE SXPLAYER"
        git clone https://github.com/stupeflix/sxplayer sxplayer
        echo "mrs -----LIST DIRECTORIES"
        ls
        echo "mrs -----DISPLAY VARIABLES"
        export NGLDIR=$HOME
        export PATH=$PATH:$HOME/.local/bin:$NGLDIR/env/bin
        echo "mrs -----CREATION DE ENV"
        mkdir $NGLDIR/env
        echo "mrs -----NGLDIR:" $NGLDIR
        echo "mrs -----PATH:" $PATH
        echo "mrs -----MAKE ALIAS"
        alias make="make -j8"
        echo "mrs -----GO INTO SXPLA"
        cd sxplayer
        echo "mrs -----MAKE INST"
        make install PREFIX=$NGLDIR/env
        echo $?
        echo "mrs -----MAKE END"
        echo "GO INTO LIBNODEGL"
        cd ../libnodegl
        echo "mrs -----MAKE INST2"
        PKG_CONFIG_PATH=$NGLDIR/lib/pkgconfig make install PREFIX=$NGLDIR/env
        echo $?
        echo "mrs -----MAKE END2"
        echo "mrs -----GO INTO NGLTOOLS"
        cd ../ngl-tools
        echo "mrs -----MAKE INST3"
        PKG_CONFIG_PATH=$NGLDIR/lib/pkgconfig make install PREFIX=$NGLDIR/env
        echo $?
        echo "mrs -----MAKE END3"


