name: 'Continuous Integration Pipeline' 

on:
  push:
    branches:    
      - master # Push events on master branch 
      - 'cboesch' # Push events to branches matching refs/heads/cboesch
      - 'mbouron' # Push events to branches matching refs/heads/mbouron
      - 'releases/**'  # Push events to branches matching refs/heads/releases/1**
  pull_request: 
    branches:    
      - master # Pull request events on master branch   
      - 'cboesch' # Pull request events to branches matching refs/heads/cboesch
      - 'mbouron' # Pull request events to branches matching refs/heads/mbouron
      - 'releases/**'  # Pull request events to branches matching refs/heads/releases/1**
  schedule:
     - cron:  '0 0 * * *' # Every day at midnight.
   
jobs:
  build_libs:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Install ubuntu libs
      run: sudo apt-get install mlocate nasm libx264-dev wget pkg-config libglfw3-dev cython python-pyqt5 python-pyqt5.qtsvg
    - name: ffmpeg
      run: |
        export PREFIX=/usr
        export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
        echo "mrs -----FFMPEG"
        wget -q https://ffmpeg.org/releases/ffmpeg-4.2.1.tar.bz2
        tar -xf ffmpeg-4.2.1.tar.bz2
        cd ffmpeg-4.2.1
        ./configure --enable-debug --disable-stripping --disable-doc \
        --disable-autodetect --enable-zlib --disable-everything \
        --enable-filter='aformat,aresample,asetnsamples,asettb,copy,format,fps,hflip,settb,scale,transpose,vflip' \
        --disable-programs --enable-avdevice --enable-swscale --enable-swresample \
        --enable-bsf='aac_adtstoasc,h264_mp4toannexb' \
        --enable-demuxer='aac,image_jpeg_pipe,image_pgm_pipe,image_png_pipe,rawvideo,mp3,mp4,mov,wav,flac,matroska,mpegts' \
        --enable-decoder='mjpeg,png,rawvideo,mp3,pcm_s16le,pcm_s16be,mpeg4,aac,pgm,flac,webp,wmv1,wmv2,wmv3,h264' \
        --enable-parser='mjpeg,png,h264,aac,flac' \
        --enable-muxer=mp4,matroska \
        --enable-encoder=libx264 \
        --enable-protocol='file,http' --enable-shared --disable-static --prefix=$PREFIX 
        sudo make -j8
        echo "mrs -----FFMPEG END"
        sudo make install 
        sudo updatedb
        echo $?
        find $PREFIX
    - name: Build sxplayer ngl-tools libnodegl 
      run: |
        export PREFIX=/usr
        export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
        echo "mrs -----WHO AM I"
        lsb_release -a 
        echo "mrs -----LIST DIRECTORIES"
        ls  
        echo "mrs -----CLONE SXPLAYER"
        wget -q https://github.com/Stupeflix/sxplayer/archive/v9.5.0.tar.gz -O sxplayer.tar.gz
        tar -xf sxplayer.tar.gz
        echo "mrs -----LIST DIRECTORIES"
        ls
        echo "mrs -----DISPLAY VARIABLES"
        
        export PATH=$PATH:$HOME/.local/bin:$PREFIX/bin
        echo "mrs -----CREATION DE ENV"
        
        
        echo "mrs -----PATH:" $PATH
        echo "mrs -----MAKE ALIAS"
        alias make="make -j8"
        echo "mrs -----GO INTO SXPLA"
        cd sxplayer-9.5.0
        echo "mrs -----MAKE INST"
        sudo make install PREFIX=$PREFIX SHARED=yes
        echo $?
        echo "mrs -----MAKE END"
        echo "GO INTO LIBNODEGL"
        cd ../libnodegl
        echo "mrs -----MAKE INST2"
        sudo make install PREFIX=$PREFIX SHARED=yes
        echo $?
        echo "mrs -----MAKE END2"
        echo "mrs -----GO INTO NGLTOOLS"
        cd ../ngl-tools
        echo "mrs -----MAKE INST3"
        sudo make install PREFIX=$PREFIX
        echo $?
        find $PREFIX
        echo "mrs -----MAKE END3"
        cd ..
        ls

    - name: Python packages 
      run: |
        export PREFIX=/usr
        export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
        echo "mrs -----UPDATE"
        sudo apt-get update
        echo "mrs -----PYTHONPIP"
        sudo apt-get install python-pip
        echo "mrs -----VERSION"
        pip2 --version
        echo "mrs -----PYNODEGL"
        sudo pip2 install --user -e ./pynodegl
        echo "mrs -----pynodegl2"
        sudo pip2 install --user -r ./pynodegl-utils/requirements.txt
        echo "mrs -----pynodegl3"
        sudo pip2 install --user -e ./pynodegl-utils
        echo "mrs -----libnodegl"
        pkg-config --modversion libnodegl  

    - name: Run tests_api
      run: |
        echo "mrs -----GO INTO TESTS"
        cd tests
        ls 
        echo "mrs -----make tests_api "
        sudo make tests_api 
 