name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Install ubuntu libs
      run: sudo apt-get install pkg-config libavformat-dev libavutil-dev libavfilter-dev libavcodec-dev libglfw3-dev cython python-pyqt5 python-pyqt5.qtsvg
    - name: Create repo with my node.gl.ci repo and needed sxplayer
      run: |
        echo "mrs -----LIST DIRECTORIES"
        ls  
        echo "mrs -----CLONE SXPLAYER"
        git clone https://github.com/stupeflix/sxplayer sxplayer
        echo "mrs -----LIST DIRECTORIES"
        ls
        echo "mrs -----DISPLAY VARIABLES"
        export NGLDIR=$HOME
        export PATH=$PATH:$HOME/.local/bin:$NGLDIR/env/bin
        echo "mrs -----CREATION DE ENV"
        mkdir $NGLDIR/env
        echo "mrs -----NGLDIR:" $NGLDIR
        echo "mrs -----PATH:" $PATH
        echo "mrs -----MAKE ALIAS"
        alias make="make -j8"
        echo "mrs -----GO INTO SXPLA"
        cd sxplayer
        echo "mrs -----MAKE INST"
        make install PREFIX=$NGLDIR/env
        echo $?
        echo "mrs -----MAKE END"
        echo "GO INTO LIBNODEGL"
        cd ../libnodegl
        echo "mrs -----MAKE INST2"
        PKG_CONFIG_PATH=$NGLDIR/env/lib/pkgconfig make install PREFIX=$NGLDIR/env
        echo $?
        echo "mrs -----MAKE END2"
        echo "mrs -----GO INTO NGLTOOLS"
        cd ../ngl-tools
        echo "mrs -----MAKE INST3"
        PKG_CONFIG_PATH=$NGLDIR/env/lib/pkgconfig make install PREFIX=$NGLDIR/env
        echo $?
        echo "mrs -----MAKE END3"


