name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Install ubuntu libs
      run: sudo apt-get install libavfilter-dev  libavcodec-dev libglfw3-dev cython python-pyqt5 python-pyqt5.qtsvg
    - name: Create repo with my node.gl.ci repo and needed sxplayer
      run: |
        echo $HOME
        echo $(ls)
        git clone https://github.com/stupeflix/sxplayer 
        echo $?
        echo $(ls)
    - name: C packages
      run: |
        alias make="make -j8"
        echo $?
        echo $(ls)
        cd sxplayer
        echo $?
        echo $(ls)
        make install PREFIX=/tmp/env
        cd libnodegl
        PKG_CONFIG_PATH=/tmp/env/lib/pkgconfig make install PREFIX=/tmp/env
        cd ngl-tools
        PKG_CONFIG_PATH=/tmp/env/lib/pkgconfig make install PREFIX=/tmp/env
        
