name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
#    - name: Install ubuntu libs
#      run: sudo apt-get install libavfilter-dev  libavcodec-dev libglfw3-dev cython python-pyqt5 python-pyqt5.qtsvg
    - name: Create repo with my node.gl.ci repo and needed sxplayer
      run: |
        echo "home:" $HOME
        ls -al 
        mkdir .hiddendir
        ls -al 
        cp * .hiddendir -R
        ls -al 

        export NGLDIR=$HOME/ngl-build
        echo "NGLDIR:" $NGLDIR
        
        export PATH=$PATH:$HOME/.local/bin:$NGLDIR/env/bin
        echo "PATH:" $PATH

        mkdir -p $NGLDIR
        ls -al 

        mkdir -p $NGLDIR/node.gl.ci
        ls -al 

        mv .hiddendir/* $NGLDIR/node.gl.ci
        ls -al

        mkdir -p $NGLDIR/env
        ls -al 

        git clone https://github.com/stupeflix/sxplayer $NGLDIR/sxplayer
        
    - name: C packages
      run: |
        alias make="make -j8"
        cd $NGLDIR/sxplayer
        echo $(ls)
        echo $?
        make install PREFIX=$NGLDIR/env
        echo $(ls)
        echo $?
        cd $NGLDIR/node.gl.ci/libnodegl
        echo $(ls)
        echo $?
        PKG_CONFIG_PATH=$NGLDIR/env/lib/pkgconfig make install PREFIX=$NGLDIR/env
        echo $(ls)
        echo $?
        cd $NGLDIR/node.gl.ci/ngl-tools
        echo $(ls)
        echo $?
        PKG_CONFIG_PATH=$NGLDIR/env/lib/pkgconfig make install PREFIX=$NGLDIR/env # 
        echo $(ls)
        echo $?