name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install ubuntu libs
      run: sudo apt-get install nasm wget pkg-config libglfw3-dev cython python-pyqt5 python-pyqt5.qtsvg
    - name: ffmpeg
      run: |
        echo "mrs -----FFMPEG"
        wget https://ffmpeg.org/releases/ffmpeg-4.2.1.tar.bz2
        tar -xf ffmpeg-4.2.1.tar.bz2
        cd ffmpeg-4.2.1
        ./configure --enable-debug --disable-stripping --disable-doc \
        --disable-autodetect --enable-zlib --disable-everything \
        --enable-filter='aformat,aresample,asetnsamples,asettb,copy,format,fps,hflip,settb,scale,transpose,vflip' \
        --disable-programs --enable-avdevice --enable-swresample \
        --enable-bsf='aac_adtstoasc,h264_mp4toannexb' \
        --enable-demuxer='aac,image_jpeg_pipe,image_pgm_pipe,image_png_pipe,rawvideo,mp3,mp4,mov,wav,flac,matroska,mpegts' \
        --enable-decoder='mjpeg,png,rawvideo,mp3,pcm_s16le,pcm_s16be,mpeg4,aac,pgm,flac,h264' \
        --enable-parser='mjpeg,png,h264,aac,flac' \
        --enable-protocol='file,http'--disable-file --without-pic --disable-shared --prefix=$HOME
        make -j8
        echo "mrs -----FFMPEG END"
        sudo make install 
        echo $?
        ls 
    - name: Build sxplayer ngl-tools libnodegl 
      run: |
        echo "mrs -----WHO AM I"
        lsb_release -a 
        echo "mrs -----LIST DIRECTORIES"
        ls  
        echo "mrs -----CLONE SXPLAYER"
        git clone https://github.com/stupeflix/sxplayer sxplayer
        echo "mrs -----LIST DIRECTORIES"
        ls
        echo "mrs -----DISPLAY VARIABLES"
        export NGLDIR=$HOME
        export PATH=$PATH:$HOME/.local/bin:$NGLDIR/env/bin
        echo "mrs -----CREATION DE ENV"
        mkdir $NGLDIR/env
        echo "mrs -----NGLDIR:" $NGLDIR
        echo "mrs -----PATH:" $PATH
        echo "mrs -----MAKE ALIAS"
        alias make="make -j8"
        echo "mrs -----GO INTO SXPLA"
        cd sxplayer
        echo "mrs -----MAKE INST"
        PKG_CONFIG_PATH=$NGLDIR/lib/pkgconfig make install PREFIX=$NGLDIR/env
        echo $?
        echo "mrs -----MAKE END"
        echo "GO INTO LIBNODEGL"
        cd ../libnodegl
        echo "mrs -----MAKE INST2"
        PKG_CONFIG_PATH=$NGLDIR/env/lib/pkgconfig make install PREFIX=$NGLDIR/env
        echo $?
        echo "mrs -----MAKE END2"
        echo "mrs -----GO INTO NGLTOOLS"
        cd ../ngl-tools
        echo "mrs -----MAKE INST3"
        PKG_CONFIG_PATH=$NGLDIR/env/lib/pkgconfig make install PREFIX=$NGLDIR/env
        echo $?
        echo "mrs -----MAKE END3"


    - name: Python packages 
      run: |
        export NGLDIR=$HOME
        echo "mrs -----UPDATE"
        sudo apt-get update
        echo "mrs -----PYTHONPIP"
        sudo apt-get install python-pip
        echo "mrs -----VERSION"
        pip --version
        echo "mrs -----PYNODEGL"
        PKG_CONFIG_PATH=$NGLDIR/env/lib/pkgconfig pip2 install --user -e ./pynodegl
        echo "mrs -----pynodegl2"
        pip2 install --user -r ./pynodegl-utils/requirements.txt
        echo "mrs -----pynodegl3"
        pip2 install --user -e ./pynodegl-utils
        echo "mrs -----libnodegl"
        PKG_CONFIG_PATH=$NGLDIR/env/lib/pkgconfig pkg-config --modversion libnodegl  