name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencie
      run: sudo apt-get install libavfilter-dev  libavcodec-dev libglfw3-devs cython python-pyqt5 python-pyqt5.qtsvg
 
