name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Install ubuntu libs
      run: sudo apt-get install libavfilter-dev  libavcodec-dev libglfw3-dev cython python-pyqt5 python-pyqt5.qtsvg
    - name: Create repo with my node.gl.ci repo and needed sxplayer
      run: |
        mkdir ngl-build
        ls -al 